{ DEBUG_NONE, "No debugging"},
{ DEBUG_ERRS, "Verbose error reporting"},
{ DEBUG_INIT, "Debug initialization"},
{ DEBUG_SOCKETS, "Debug socket operations"},
{ DEBUG_PROCESSES, "Debug processes (fork/reap/etc)"},
{ DEBUG_SPIFFY, "Debug the spiffy sending code"},
{ DEBUG_CHUNKS, "Debug chunk parsing functions"},
{ DEBUG_COMMANDS, "Debug commands (e.g. GET)"},
{ DEBUG_PACKETS, "Debug packet creation"},
{ DEBUG_DOWNLOAD, "Debug data download"},
{ DEBUG_UPLOAD, "Debug data upload"},
{ DEBUG_ALL, "Show all debug messages"},
