{ DEBUG_NONE, "No debugging"},
{ DEBUG_ERRS, "Verbose error reporting"},
{ DEBUG_INIT, "Debug initialization"},
{ DEBUG_SOCKETS, "Debug socket operations"},
{ DEBUG_COMMANDS, "Debug commands (e.g. GET)"},
{ DEBUG_PROCESSES, "Debug processes (fork/reap/etc)"},
{ DEBUG_SPIFFY, "Debug the spiffy sending code"},
